
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot-summary
    username: root
    password: root
    hikari:
      pool-name: HikariCP
      connection-timeout: 3000
      connection-test-query: SELECT 1
      maximum-pool-size: 64
      minimum-idle: 4
      idle-timeout: 180000
      max-lifetime: 1800000


  rabbitmq:
    addresses: [localhost:5672]
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
