management:
  server:
    port: 9001
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  flyway:
    out-of-order: true
    clean-disabled: true
    fail-on-missing-locations: true
  #####################################################################################################################
  # default location = db.migration
  #  create table manually
  #  CREATE TABLE IF NOT EXISTS flyway_schema_history
  #  (
  #      installed_rank INT NOT NULL
  #          PRIMARY KEY,
  #      VERSION VARCHAR(50) NULL,
  #      description VARCHAR(200) NOT NULL,
  #      TYPE VARCHAR(20) NOT NULL,
  #      script VARCHAR(1000) NOT NULL,
  #      CHECKSUM INT NULL,
  #      installed_by VARCHAR(100) NOT NULL,
  #      installed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  #      execution_time INT NOT NULL,
  #      success TINYINT(1) NOT NULL
  #  );
  #
  #  CREATE INDEX flyway_schema_history_s_idx
  #      ON flyway_schema_history (success);
  #####################################################################################################################


